### PR TITLE
refactor ConditionalFieldsApp

### PR DESCRIPTION
**Pull request by jamesarosen**

### CODE REVIEW

**Comment by jamesarosen** [comment]
@skipjac please let me know if this looks good. It's possible I'm not understanding a use-case.

**Comment by skipjac** [comment]
@jamesarosen this code works why all the changes? One thing I never did get working is the array in array you have built out with. 

```
dolphin: [ fieldToToggleOne, fieldToToggleTwo ]
```

that is why I use the concat function. 

```
dolphin: [].concat(projectRequest, otherHelpesk)
```

**Comment by jamesarosen** [comment]
The changes are to make it easier to read. I was trying to debug someone's app today and I had quite a bit of trouble. In particular, having instance variables called `type1` and `type2` and an instance method called `typeII` is confusing.

There was also a small bug: if the value of the trigger field (what you were calling `this.type1` and `this.type2`) wasn't in the dictionary (your `moodFieldMap`), then you were passing `undefined` to `show`. This threw an exception because that calls `fields.forEach`. I added a guard so that we don't try to call `show` if we didn't find any fields.

Lastly, I didn't understand why you were defining all the custom field values as arrays of one item and then concatenating them. The following are equivalent:

``` javascript
[ 'foo', 'bar', 'baz' ]
[].concat(['foo'], ['bar'], ['baz'])
```

**Comment by jamesarosen** [comment]
There's one other benefit to this updated version: people can list non-custom fields as fields to toggle since `show` and `hide` don't assume a `custom_field_` prefix.

**Comment by skipjac** [comment]
this might be a bad example because it's only calling one field if you have more then one field in the arrays you build out which is the more common case you end up with 

```
var one = ['foo', 'bar']
var two = ['baz', 'fub']
var newarr = [one, two]
newarr
[ Array[2]
   0: "foo"
   1: "bar", 
Array[2]
  0: "baz"
  1: "fub"
]
```

this will not work through the show and hide correctly. 

but when you concat them each element of the array is added to the end giving you a new array which is in the format that the show and hide function can handle 

```
var skiparr = [].concat(one, two)
skiparr
["foo", "bar", "baz", "fub"]
```

**Comment by jamesarosen** [comment]
Yes, if you're defining collections of fields then you'll need to use `concat`. This app doesn't do that, though it does leave open that possibility. I can change back to arrays and `concat`.

**Comment by skipjac** [comment]
please change back the arrays to concat and I will be happy to update this.

**Comment by jamesarosen** [comment]
Updated.

**Pull request merged**
